/*
 * Demo API
 * Demo
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoApi) {
      root.DemoApi = {};
    }
    root.DemoApi.PasswordResetConfirm = factory(root.DemoApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PasswordResetConfirm model module.
   * @module model/PasswordResetConfirm
   * @version v1
   */

  /**
   * Constructs a new <code>PasswordResetConfirm</code>.
   * @alias module:model/PasswordResetConfirm
   * @class
   * @param newPassword1 {String} 
   * @param newPassword2 {String} 
   * @param uid {String} 
   * @param token {String} 
   */
  var exports = function(newPassword1, newPassword2, uid, token) {
    this.newPassword1 = newPassword1;
    this.newPassword2 = newPassword2;
    this.uid = uid;
    this.token = token;
  };

  /**
   * Constructs a <code>PasswordResetConfirm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PasswordResetConfirm} obj Optional instance to populate.
   * @return {module:model/PasswordResetConfirm} The populated <code>PasswordResetConfirm</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('new_password1'))
        obj.newPassword1 = ApiClient.convertToType(data['new_password1'], 'String');
      if (data.hasOwnProperty('new_password2'))
        obj.newPassword2 = ApiClient.convertToType(data['new_password2'], 'String');
      if (data.hasOwnProperty('uid'))
        obj.uid = ApiClient.convertToType(data['uid'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} newPassword1
   */
  exports.prototype.newPassword1 = undefined;

  /**
   * @member {String} newPassword2
   */
  exports.prototype.newPassword2 = undefined;

  /**
   * @member {String} uid
   */
  exports.prototype.uid = undefined;

  /**
   * @member {String} token
   */
  exports.prototype.token = undefined;

  return exports;

}));
