/*
 * Demo API
 * Demo
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoApi) {
      root.DemoApi = {};
    }
    root.DemoApi.UserDetails = factory(root.DemoApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UserDetails model module.
   * @module model/UserDetails
   * @version v1
   */

  /**
   * Constructs a new <code>UserDetails</code>.
   * @alias module:model/UserDetails
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param email {String} 
   */
  var exports = function(firstName, lastName, email) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
  };

  /**
   * Constructs a <code>UserDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDetails} obj Optional instance to populate.
   * @return {module:model/UserDetails} The populated <code>UserDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password1'))
        obj.password1 = ApiClient.convertToType(data['password1'], 'String');
      if (data.hasOwnProperty('password2'))
        obj.password2 = ApiClient.convertToType(data['password2'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} password1
   */
  exports.prototype.password1 = undefined;

  /**
   * @member {String} password2
   */
  exports.prototype.password2 = undefined;

  return exports;

}));
