/*
 * Demo API
 * Demo
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DemoApi);
  }
}(this, function(expect, DemoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DemoApi.LoginApi();
  });

  describe('(package)', function() {
    describe('LoginApi', function() {
      describe('loginCreate', function() {
        it('should call loginCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for loginCreate call and complete the assertions
          /*
          var data = new DemoApi.Login();
          data.email = "";
          data.password = "";

          instance.loginCreate(data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DemoApi.Login);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.password).to.be.a('string');
            expect(data.password).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
