/*
 * Demo API
 * Demo
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DemoApi);
  }
}(this, function(expect, DemoApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PasswordResetConfirm', function() {
      beforeEach(function() {
        instance = new DemoApi.PasswordResetConfirm();
      });

      it('should create an instance of PasswordResetConfirm', function() {
        // TODO: update the code to test PasswordResetConfirm
        expect(instance).to.be.a(DemoApi.PasswordResetConfirm);
      });

      it('should have the property newPassword1 (base name: "new_password1")', function() {
        // TODO: update the code to test the property newPassword1
        expect(instance).to.have.property('newPassword1');
        // expect(instance.newPassword1).to.be(expectedValueLiteral);
      });

      it('should have the property newPassword2 (base name: "new_password2")', function() {
        // TODO: update the code to test the property newPassword2
        expect(instance).to.have.property('newPassword2');
        // expect(instance.newPassword2).to.be(expectedValueLiteral);
      });

      it('should have the property uid (base name: "uid")', function() {
        // TODO: update the code to test the property uid
        expect(instance).to.have.property('uid');
        // expect(instance.uid).to.be(expectedValueLiteral);
      });

      it('should have the property token (base name: "token")', function() {
        // TODO: update the code to test the property token
        expect(instance).to.have.property('token');
        // expect(instance.token).to.be(expectedValueLiteral);
      });

    });
  });

}));
